<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>StealthBypass · Control Center</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap');
    :root{--ink:#f1f3ff;--muted:#8990aa;--cyan:#57f3d2;--blue:#7586ff;--bg:#080a10;--panel:rgba(18,22,34,.8);--line:rgba(169,184,255,.14);--danger:#ff6982}*{box-sizing:border-box}body{min-width:320px;margin:0;color:var(--ink);font:14px/1.45 Manrope,Arial,sans-serif;background:radial-gradient(900px 600px at 93% 0,#19295a88 0%,transparent 62%),radial-gradient(700px 500px at 15% 96%,#123b3c70 0%,transparent 65%),var(--bg)}
    .app{display:grid;grid-template-columns:270px minmax(0,1fr);min-height:100vh}.side{padding:31px 16px;background:#0a0c13ad;border-right:1px solid var(--line)}.brand{display:flex;align-items:center;gap:11px;padding:0 12px 45px;font-size:18px;font-weight:800;letter-spacing:-.7px}.sigil{display:grid;place-items:center;width:32px;height:32px;border:1px solid #6bfff033;border-radius:10px;color:var(--cyan);background:linear-gradient(135deg,#1f5168,#16322f);box-shadow:inset 0 0 17px #55f0d62b,0 0 22px #57f3d222;font-size:18px}.brand em{color:var(--cyan);font-style:normal}.nav-caption{margin:0 12px 9px;color:#555d75;font-size:10px;font-weight:800;letter-spacing:.16em;text-transform:uppercase}.nav{display:flex;align-items:center;gap:12px;width:100%;margin:4px 0;padding:11px 12px;border:1px solid transparent;border-radius:9px;background:transparent;color:#858da5;text-align:left;font-weight:600}.nav:hover,.nav.active{border-color:#737aff2b;color:#f4f5ff;background:linear-gradient(90deg,#6174ff1f,transparent)}.nav.active:before{content:'';width:5px;height:5px;border-radius:50%;background:var(--cyan);box-shadow:0 0 9px var(--cyan)}.nav span{margin-left:auto;border:1px solid #63eed02a;border-radius:10px;padding:1px 7px;color:var(--cyan);font:11px 'DM Mono',monospace}.user{display:flex;align-items:center;gap:10px;margin:45px 10px 0;padding:16px 0;border-top:1px solid var(--line)}.avatar{display:grid;place-items:center;width:31px;height:31px;border-radius:50%;background:#1d2847;color:#aab7ff;font-size:12px;font-weight:800}.user b,.user small{display:block}.user small{color:var(--muted);font-size:11px}
    main{width:min(1390px,100%);margin:auto;padding:39px clamp(20px,5vw,74px)}.eyebrow{color:var(--cyan);font:11px 'DM Mono',monospace;letter-spacing:.13em;text-transform:uppercase}.top{display:flex;justify-content:space-between;gap:25px;align-items:end;margin-bottom:32px}h1{margin:6px 0 6px;font-size:clamp(27px,3vw,38px);letter-spacing:-1.8px;line-height:1.12}.lead{margin:0;color:var(--muted)}.online{display:flex;align-items:center;gap:8px;padding:8px 11px;border:1px solid #4ce9d031;border-radius:20px;color:#bac5d6;background:#14363142;font:11px 'DM Mono',monospace}.orb{width:7px;height:7px;border-radius:50%;background:var(--cyan);box-shadow:0 0 10px var(--cyan)}
    .stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:16px}.stat,.section{border:1px solid var(--line);background:linear-gradient(120deg,var(--panel),rgba(12,15,24,.85));box-shadow:0 12px 35px #00000018}.stat{position:relative;overflow:hidden;padding:18px;border-radius:12px}.stat:after{content:'';position:absolute;right:-22px;bottom:-29px;width:90px;height:90px;border:1px solid #8596ff20;border-radius:50%;box-shadow:0 0 0 15px #8596ff0c}.stat label{color:var(--muted);font-size:12px}.value{margin:8px 0 0;font:700 28px 'DM Mono',monospace;letter-spacing:-1.5px}.value.cyan{color:var(--cyan)}.detail{margin-top:6px;color:#778098;font-size:11px}.section{padding:22px;border-radius:12px}.section+.section{margin-top:16px}.section-head{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:19px}h2{margin:0;font-size:15px;letter-spacing:-.3px}.api{color:#78819a;font:11px 'DM Mono',monospace}.form{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:11px;align-items:end}label{display:block;margin:0 0 7px;color:#8992aa;font-size:11px;font-weight:700;letter-spacing:.02em}input,select{width:100%;height:42px;padding:0 12px;color:var(--ink);border:1px solid #374058;background:#0b0e16;border-radius:7px;outline:0;font:13px 'DM Mono',monospace}input:focus,select:focus{border-color:#63f2d4aa;box-shadow:0 0 0 3px #53edcf14}select option{background:#111520}.generate{height:42px;padding:0 18px;border:1px solid #86fff13d;border-radius:7px;color:#061310;background:linear-gradient(135deg,#52efd2,#6ab7ff);box-shadow:0 6px 22px #50eed03d;font-weight:800;white-space:nowrap}.generate:hover{filter:brightness(1.08)}
    .search{width:235px;background:#0b0e16 url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' stroke='%238992aa' stroke-width='1.8' width='16' height='16'%3E%3Ccircle cx='7' cy='7' r='4.5'/%3E%3Cpath d='m10.5 10.5 3.5 3.5'/%3E%3C/svg%3E") no-repeat 12px center;padding-left:35px}.error{margin:-4px 0 16px;padding:10px 12px;border:1px solid #ff6b8140;border-radius:7px;color:#ff9bac;background:#ff5f7510;font-size:12px}.table-wrap{overflow:auto}table{width:100%;min-width:690px;border-collapse:collapse}th{padding:0 12px 9px;color:#667089;text-align:left;font:10px 'DM Mono',monospace;letter-spacing:.1em;text-transform:uppercase}td{padding:15px 12px;border-top:1px solid var(--line)}code{padding:5px 7px;border:1px solid #6e7aff22;border-radius:5px;color:#cbd2ff;background:#1d213533;font:12px 'DM Mono',monospace}.state{display:inline-flex;align-items:center;gap:7px;padding:4px 8px;border-radius:15px;font-size:11px;font-weight:700}.state:before{content:'';width:5px;height:5px;border-radius:50%;background:currentColor}.active{color:var(--cyan);background:#37d8bd11}.used{color:#ffce76;background:#f0b85612}.expired{color:#9ba1b1;background:#8b91a316}.muted{color:var(--muted)}.delete{padding:6px 9px;border:1px solid #ff6b8133;border-radius:6px;color:#ff8799;background:#ff5f7510;font-size:11px;font-weight:700}.delete:hover{background:#ff5f7524}.empty{padding:32px;color:var(--muted);text-align:center}#toast{position:fixed;right:22px;bottom:22px;transform:translateY(95px);padding:12px 15px;border:1px solid #60eed354;border-radius:8px;background:#102722;color:#baffed;box-shadow:0 12px 35px #0007;transition:.25s}#toast.show{transform:translateY(0)}
    @media(max-width:860px){.app{grid-template-columns:1fr}.side{display:none}main{padding:27px 16px}.stats{grid-template-columns:1fr}.form{grid-template-columns:1fr 1fr}.generate{grid-column:1/-1}.top,.section-head{align-items:flex-start;flex-direction:column}.search{width:100%}}@media(max-width:480px){.form{grid-template-columns:1fr}}
  </style>
</head>
<body>
  <div class="app"><aside class="side"><div class="brand"><span class="sigil">⌁</span>Stealth<em>Bypass</em></div><p class="nav-caption">Контроль</p><button class="nav active">Обзор</button><button class="nav">Ключи <span id="side-count">0</span></button><button class="nav">HWID-привязки</button><p class="nav-caption" style="margin-top:28px">Система</p><button class="nav">Журнал событий</button><button class="nav">Параметры</button><div class="user"><div class="avatar">SB</div><div><b>Администратор</b><small>Owner access</small></div></div></aside>
  <main><header class="top"><div><div class="eyebrow">StealthBypass / Control center</div><h1>Управление доступом</h1><p class="lead">Выпускайте ключи и контролируйте HWID-привязки в одном месте.</p></div><div class="online"><span class="orb"></span> LOCAL INSTANCE</div></header>
  <section class="stats"><article class="stat"><label>Всего ключей</label><div class="value" id="total">0</div><div class="detail">в базе доступа</div></article><article class="stat"><label>Активные</label><div class="value cyan" id="active-count">0</div><div class="detail">ожидают активации</div></article><article class="stat"><label>HWID привязано</label><div class="value" id="used-count">0</div><div class="detail">уникальных устройств</div></article></section>
  <section class="section"><div class="section-head"><h2>Новый ключ доступа</h2><span class="api">POST /api/keys</span></div><div class="form"><div><label for="prefix">Префикс</label><input id="prefix" value="STL" maxlength="10"></div><div><label for="duration">Срок действия</label><select id="duration"><option value="30">30 дней</option><option value="7">7 дней</option><option value="90">90 дней</option><option value="forever">Навсегда</option></select></div><div><label for="amount">Количество</label><select id="amount"><option>1 ключ</option><option disabled>Пакет (скоро)</option></select></div><button class="generate" id="create">+ Сгенерировать</button></div></section>
  <section class="section"><div class="section-head"><h2>Реестр ключей</h2><input class="search" id="search" placeholder="Найти ключ"></div><div class="error" id="error" hidden></div><div class="table-wrap"><table><thead><tr><th>Код доступа</th><th>Состояние</th><th>HWID</th><th>Действует до</th><th>Создан</th><th></th></tr></thead><tbody id="rows"></tbody></table><div class="empty" id="empty">В реестре нет ключей.</div></div></section></main></div><div id="toast" role="status"></div>
  <script>
    let allKeys=[],lastSignature='',refreshing=false,creating=false;const $=s=>document.querySelector(s);const show=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),2400)};const showError=t=>{const e=$('#error');e.textContent=t;e.hidden=!t};const cls=s=>s==='Активен'?'active':s==='Использован'?'used':'expired';
    function render(){const q=$('#search').value.trim().toLowerCase(),list=allKeys.filter(k=>k.key.toLowerCase().includes(q));$('#rows').innerHTML=list.map(k=>`<tr><td><code>${k.key}</code></td><td><span class="state ${cls(k.status)}">${k.status}</span></td><td class="muted">${k.hwid}</td><td>${k.expires}</td><td class="muted">${k.created}</td><td><button class="delete" data-key="${k.key}">Удалить</button></td></tr>`).join('');$('#empty').hidden=Boolean(list.length);$('#total').textContent=allKeys.length;$('#side-count').textContent=allKeys.length;$('#active-count').textContent=allKeys.filter(k=>k.status==='Активен').length;$('#used-count').textContent=allKeys.filter(k=>k.status==='Использован').length}
    async function api(url,options){const response=await fetch(url,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||data.reason||'Ошибка соединения с сервером');return data}async function load(){if(refreshing)return;refreshing=true;try{const fresh=await api('/api/keys');const signature=JSON.stringify(fresh);if(signature!==lastSignature){allKeys=fresh;lastSignature=signature;render()}showError('')}catch(error){showError(`Не удалось загрузить ключи: ${error.message}`)}finally{refreshing=false}}$('#search').addEventListener('input',render);$('#create').addEventListener('click',async()=>{if(creating)return;creating=true;const button=$('#create');button.disabled=true;button.textContent='Создаём…';try{const item=await api('/api/keys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prefix:$('#prefix').value,duration:$('#duration').value})});allKeys.unshift(item);lastSignature=JSON.stringify(allKeys);render();showError('');show(`Создан ${item.key}`)}catch(error){showError(`Не удалось создать ключ: ${error.message}`)}finally{creating=false;button.disabled=false;button.textContent='+ Сгенерировать'}});$('#rows').addEventListener('click',async e=>{const key=e.target.dataset.key;if(!key)return;try{await api('/api/keys/'+encodeURIComponent(key),{method:'DELETE'});allKeys=allKeys.filter(k=>k.key!==key);lastSignature=JSON.stringify(allKeys);render();show('Ключ удалён')}catch(error){showError(`Не удалось удалить ключ: ${error.message}`)}});load();setInterval(load,1000);
  </script>
</body>
</html>
